### ISSUE TITLE
$GITHUB_TOKEN is not set correctly

### ISSUE THREAD

**Issue by justinwoo** [purescript-node/purescript-node-fs-aff#22]
See Travis docs publishing failures in https://travis-ci.org/purescript-node/purescript-node-fs-aff

**Comment by garyb** [comment]
Fixed!

**Comment by justinwoo** [comment]
Thanks!

**Comment by garyb** [comment]
The latest auto-publish still failed due to `package.json` not being ignored though, so I've added that to the `.gitignore` too.
