### ISSUE TITLE
The example on the readme is outdated

### ISSUE THREAD

**Issue by danielo515** [purescript-node/purescript-node-fs-aff#23]
Hello,
Today I spent a good amount of time until I realized that the example you showcase on the readme is outdated. I'm a begginer on Purescript and I don't realize this kind of things at first sight, but stuff like `(/= ".")` is no longer supported and Node.Fs.readDir does not returns a List anymore.
Luckily there is a working and up to date example on the test directory, so the update should be straightforward.

**Comment by JordanMartinez** [comment]
Closing as this repo is deprecated.
