### ISSUE TITLE
Add to Pursuit?

### ISSUE THREAD

**Issue by paf31** [purescript-node/purescript-node-fs-aff#4]

**Comment by felixSchl** [comment]
I gave it a shot this morning, but I cannot compile, see #5 and pursuit won't accept builds made with psc 0.7.0 I would be grateful if you could take a look at it. I haven't tried checking out psc 0.7.1 specifically yet, but I guess we want to have it compile first anyway.

**Comment by felixSchl** [comment]
Ok, now that #5 is out of the way, `psc-publish --dry-run` completes fine, but when I try to `psc-publish > pursuit.json`, it complains that the git working tree is dirty. But it needs to be dirty, since I need to `bower install`, otherwise it won't compile. What am I missing?

**Comment by paf31** [comment]
But `bower install` shouldn't modify the working tree.

**Comment by felixSchl** [comment]
Ah, it was dirty because of `pursuit.json`. Makes sense, since `bower_components` is in the `.gitignore`.

**Comment by felixSchl** [comment]
http://pursuit.purescript.org/packages/purescript-node-fs-aff/0.1.2

**Comment by paf31** [comment]
:+1: Nice, thanks!

**Comment by garyb** [comment]
I got tripped up by that too :smile: I tend to `psc-publish > ../pursuit.json` now.
