### ISSUE TITLE
Cannot compile with purescript 0.7.2.0

### ISSUE THREAD

**Issue by felixSchl** [purescript-node/purescript-node-fs-aff#5]
```
$ psc --version
0.7.2.0
```

```
$ bower install && npm install && gulp example
....
Compiling Data.Enum
Error found:
Error in module Data.Enum:
Error in value declaration enumChar:
Error at /Users/felix/projects/purescript-node-fs-aff/bower_components/purescript-enums/src/Data/Enum.purs line 113, column 1 - line 121, column 1:
  Overlapping instances found for Prelude.Bounded Prim.Char:
  Data.Char.boundedChar
  Prelude.boundedChar
See https://github.com/purescript/purescript/wiki/Error-Code-OverlappingInstances for more information, or to contribute content related to this error.
```

**Comment by felixSchl** [comment]
Since we do not depend on that package directly, I don't know where the dependency comes from and what to change to bring in a (possibly updated?) package.

**Comment by garyb** [comment]
This is actually down to `prelude` v0.1.2 mixed with an version of `strings` pre-0.7.0... [more discussion here](https://github.com/purescript/purescript-enums/issues/9).

Bumping the `purescript-node-fs` dependency will fix the issue for this package too.

**Comment by garyb** [comment]
The bump is necessary to remove the orphan instance in strings, by the way. Anything relying on the old strings won't compile in psc 0.7.3.

**Comment by felixSchl** [comment]
@garyb 

I updated all dependencies, they are now at:

```
  "dependencies": {
    "purescript-aff": "~0.11.3",
    "purescript-node-fs": "~0.8.1",
    "purescript-either": "~0.2.2",
    "purescript-node-path": "~0.4.0"
  }
```

I still get the same issue.

**Comment by garyb** [comment]
Did you remove the `output` folder before recompiling?

**Comment by felixSchl** [comment]
That was it, thanks!
