### ISSUE TITLE
fdOpen, fdRead etc??

### ISSUE THREAD

**Issue by timbod7** [purescript-node/purescript-node-fs-aff#7]
Why are there no equivalents to  the lower level fd\* function (from purescript-node-fs) in this library?

Am I right in thinking that there is currently no way to incrementally process a large file in Aff?

**Comment by felixSchl** [comment]
It covers all functions exported by [Node.FS.Async](https://github.com/purescript-node/purescript-node-fs/blob/master/src/Node/FS/Async.purs) by simply draping over their callback type.

I guess you would want access to functions wrapping [fs.read](https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback) and friends. It would probably be easiest to add this functionality to purescript-node-fs first, then update this async wrapper.
